### PR TITLE
Review options dialog tooltips and some labels.

### PR DESCRIPTION
**Pull request by step-**
Hi, I tried to improve tooltips (and some labels) of the options dialog without making text longer or more complicated. What do you think?
* Fixed a few typos. Rearranged some sentences to improve grammar. Shortened some sentences.  Replaced 'thumbs' with 'thumbnails'. Tried to keep sentences short.
* Did not change standard rox messages because they are already translated into many languages.

### CODE REVIEW

**Comment by jun7** [comment]
Thank you.

There are two corrections.

create_sub_dir_thumbs: This process picks a thumb from sub-dir without rox's order. e.g. If you made 0100.png and 1.png, the process picks 0100.png. Also sort options do not effect. The description describes solution of these cases.

auto_move: This option is not for pointer warp. This option is for window managers haven't window move. the pointer thing is just a collateral.
In random english:
most window managers handle window move better than rox, so you can off this option but if this is off, poiter warp in window move is disabled because the pointer warp uses window move's data.

**Comment by step-** [comment]
If you think these corrections are OK, I will update my pull request with them.

**create_sub_dir_thumbs**

When there are no thumbnails for a sub-directory, this process tries to create (max 999) thumbnails then chooses an unsorted thumbnail for display. If you don't like the choice, you can middle-click the rescan button in the toolbar to re-create sorted thumbnails.

original

When there is no thumbs in a sub dir, this process tries to create all(or 999) thumbs in the dir. If this picked a wrong thumb, re-creating thumbs in the sub dir wills solve it. Re-creating file thumbs is assigned middle click on the scan button.

**auto_move**

Enable this If your window manager does not handle window move well. When this is off, pointer warp on auto-move is disabled.

original

Normaly window managers handle window move. If this is off, the pointer warp on the auto-move is disabled too.

**Comment by jun7** [comment]
create_sub_dir_thumbs:
You have to move to the sub directory and 'Scan' button doesn't sort items but only choose first item in the sub-dir.
On parent dir, Scan button doesn't use rox's sort but uses own sort. So it is not 'unsorted thumbnail'.
And this process is not only for sub dir thumbs, it also intended to make thumbs at ones. So I suspect 'for a sub-directory'.

auto_move:
auto_move is enabled by default, and pointer warp on auto-move is very important. So 'Enable this if' is wrong.

**Comment by step-** [comment]
If you think these corrections are OK, I will update my pull request with them.

**create_sub_dir_thumbs**

When no items in a sub-directory have a thumbnail, this process tries to create (max 999) thumbnails then chooses one for display. If you don't like the choice, visit the sub-directory and middle-click the rescan button in the toolbar to choose the first item.

\original

When there is no thumbs in a sub dir, this process tries to create all(or 999) thumbs in the dir. If this picked a wrong thumb, re-creating thumbs in the sub dir wills solve it. Re-creating file thumbs is assigned middle click on the scan button.

**auto_move**

I think it's better to also change the label.

New label: Take control of window move on auto-resize

New tool tip: When this is on rox, rather than the window manager, handles window move. When this is off, pointer warp on auto-move is disabled.

original

Old label: Override control of the auto-move on the auto-resize

Old tool tip: Normaly window managers handle window move. If this is off, the pointer warp on the auto-move is disabled too.

**Comment by jun7** [comment]
Only one correction. 'Rescan' is renamed to 'Scan' because it was too long.
Thank you!

**Comment by step-** [comment]
OK, committed. Thank you.

**Pull request merged**
